from __future__ import annotations

import logging
import math
import sys
from pathlib import Path

import numpy as np
from shapely import affinity
from shapely.geometry import Polygon

from packplot.types import PackOptions, PackedPlacement, SourceObject

logger = logging.getLogger(__name__)


def _to_canvas_size(area: float, target_aspect_ratio: float) -> tuple[int, int]:
    width = max(1, math.ceil(math.sqrt(area * target_aspect_ratio)))
    height = max(1, math.ceil(area / width))
    return width, height


def _make_placement_from_center(source: SourceObject, center_xy: tuple[float, float]) -> PackedPlacement:
    cx, cy = center_xy
    local_cx, local_cy = source.hull.centroid.x, source.hull.centroid.y
    x = int(round(cx - local_cx))
    y = int(round(cy - local_cy))
    polygon = affinity.translate(source.hull, xoff=x, yoff=y)
    return PackedPlacement(
        source_path=source.source_path,
        polygon=polygon,
        angle_degrees=0.0,
        flipped=False,
        top_left=(x, y),
        image=source.cropped_image,
    )


def _adjust_to_canvas(placements: list[PackedPlacement], options: PackOptions) -> tuple[list[PackedPlacement], tuple[int, int]]:
    buffered = [p.polygon.buffer(float(options.padding) + float(options.edge_buffer), join_style=2) for p in placements]
    min_x = min(poly.bounds[0] for poly in buffered)
    min_y = min(poly.bounds[1] for poly in buffered)
    max_x = max(poly.bounds[2] for poly in buffered)
    max_y = max(poly.bounds[3] for poly in buffered)
    shift_x = -int(math.floor(min_x))
    shift_y = -int(math.floor(min_y))

    shifted: list[PackedPlacement] = []
    for p in placements:
        shifted.append(
            PackedPlacement(
                source_path=p.source_path,
                polygon=affinity.translate(p.polygon, xoff=shift_x, yoff=shift_y),
                angle_degrees=p.angle_degrees,
                flipped=p.flipped,
                top_left=(p.top_left[0] + shift_x, p.top_left[1] + shift_y),
                image=p.image,
            )
        )

    width = int(math.ceil(max_x + shift_x))
    height = int(math.ceil(max_y + shift_y))
    return shifted, (max(1, width), max(1, height))


def pack_with_circpacker(source_objects: list[SourceObject], options: PackOptions) -> tuple[list[PackedPlacement], tuple[int, int]]:
    """Pack objects into circle slots generated by `circpacker`."""
    from circpacker.core.packer import CircPacking

    required = []
    extra = float(options.padding) + float(options.edge_buffer)
    for source in source_objects:
        min_x, min_y, max_x, max_y = source.hull.bounds
        req = 0.5 * max(max_x - min_x, max_y - min_y) + extra
        required.append((req, source))
    required.sort(key=lambda x: x[0], reverse=True)

    total_area = sum(source.hull.area for source in source_objects)
    canvas_area = total_area / max(0.05, options.fill_ratio)
    cfg = options.circpacker_config
    n = len(required)
    best_relaxed: tuple[float, list[PackedPlacement]] | None = None

    for growth_step in range(max(1, cfg.max_canvas_growth_steps) + 2):
        width, height = _to_canvas_size(canvas_area, options.target_aspect_ratio)
        rect = np.array([[0.0, 0.0], [float(width), 0.0], [float(width), float(height)], [0.0, float(height)]], dtype=float)
        for depth in range(cfg.initial_depth, cfg.max_depth + 3):
            try:
                cp = CircPacking(rect, depth=depth)
            except Exception as exc:  # pragma: no cover
                logger.warning("circpacker failed at depth=%d: %s", depth, exc)
                continue
            circles = sorted(cp.listCirc, key=lambda c: c.radius, reverse=True)
            used = set()
            placements: list[PackedPlacement] = []
            success = True
            for req, source in required:
                match_idx = None
                for idx, circle in enumerate(circles):
                    if idx in used:
                        continue
                    if circle.radius >= req:
                        match_idx = idx
                        break
                if match_idx is None:
                    success = False
                    break
                used.add(match_idx)
                center = circles[match_idx].center
                placements.append(_make_placement_from_center(source, (float(center[0]), float(center[1]))))
            if success:
                placed, canvas = _adjust_to_canvas(placements, options)
                logger.info("circpacker succeeded at depth=%d growth_step=%d", depth, growth_step + 1)
                return placed, canvas

            # Relaxed fallback: use top circles and scale layout when some
            # required radii are larger than generated slots.
            if len(circles) >= n:
                top = circles[:n]
                scale = 1.0
                relaxed: list[PackedPlacement] = []
                for idx, (req, source) in enumerate(required):
                    radius = max(1e-6, float(top[idx].radius))
                    scale = max(scale, req / radius)
                scale *= 1.05
                for idx, (_, source) in enumerate(required):
                    center = top[idx].center
                    relaxed.append(
                        _make_placement_from_center(
                            source,
                            (float(center[0]) * scale, float(center[1]) * scale),
                        )
                    )
                if best_relaxed is None or scale < best_relaxed[0]:
                    best_relaxed = (scale, relaxed)
        canvas_area *= cfg.canvas_growth_factor
    if best_relaxed is not None:
        placed, canvas = _adjust_to_canvas(best_relaxed[1], options)
        logger.info("circpacker relaxed fallback used (scale=%.3f).", best_relaxed[0])
        return placed, canvas
    raise RuntimeError("circpacker could not place all shapes with current settings.")


def _import_polypacker(local_repo_path: str):
    try:
        from polypacker.packing import PolyPacker

        return PolyPacker
    except Exception:
        repo_path = Path(local_repo_path)
        if not repo_path.is_absolute():
            repo_path = Path.cwd() / repo_path
        if repo_path.exists():
            sys.path.insert(0, str(repo_path))
            from polypacker.packing import PolyPacker

            return PolyPacker
        raise


def pack_with_cell_packing(source_objects: list[SourceObject], options: PackOptions) -> tuple[list[PackedPlacement], tuple[int, int]]:
    """Pack polygons using `cell-packing` relaxation dynamics."""
    cfg = options.cell_packing_config
    PolyPacker = _import_polypacker(cfg.local_source_checkout_path)

    # Seed polygons on a coarse grid.
    n = len(source_objects)
    side = max(1, math.ceil(math.sqrt(n)))
    spacing = max(
        10.0,
        float(np.mean([math.hypot(s.cropped_image.width, s.cropped_image.height) for s in source_objects])),
    )
    polys: list[Polygon] = []
    for idx, source in enumerate(source_objects):
        row = idx // side
        col = idx % side
        x = col * spacing
        y = row * spacing
        polys.append(affinity.translate(source.hull, xoff=x, yoff=y))

    # The library's preallocation mode leaves placeholder `None` polygons that
    # break distance updates; start empty and add polygons explicitly.
    packer = PolyPacker(N=0)
    packer.add_polygons(polys)
    for _ in range(max(1, cfg.iterations)):
        packer.step(att=cfg.attraction_step, rep=cfg.repulsion_step)

    centers = np.asarray(packer.centers, dtype=float)
    center_mean = np.mean(centers, axis=0)
    centers -= center_mean

    placements = [_make_placement_from_center(source_objects[i], (centers[i, 0], centers[i, 1])) for i in range(n)]
    source_by_path = {s.source_path: s for s in source_objects}

    # Stretch shorter axis to match requested aspect ratio without compressing spacing.
    buffered = [p.polygon.buffer(float(options.padding) + float(options.edge_buffer), join_style=2) for p in placements]
    min_x = min(poly.bounds[0] for poly in buffered)
    min_y = min(poly.bounds[1] for poly in buffered)
    max_x = max(poly.bounds[2] for poly in buffered)
    max_y = max(poly.bounds[3] for poly in buffered)
    width = max(1e-6, max_x - min_x)
    height = max(1e-6, max_y - min_y)
    ratio = width / height
    if ratio < options.target_aspect_ratio:
        scale_x = options.target_aspect_ratio / ratio
        scale_y = 1.0
    else:
        scale_x = 1.0
        scale_y = ratio / options.target_aspect_ratio

    scaled: list[PackedPlacement] = []
    for p in placements:
        source = source_by_path[p.source_path]
        poly = affinity.scale(p.polygon, xfact=scale_x, yfact=scale_y, origin=(0.0, 0.0))
        cx, cy = poly.centroid.x, poly.centroid.y
        local_cx, local_cy = source.hull.centroid.x, source.hull.centroid.y
        x = int(round(cx - local_cx))
        y = int(round(cy - local_cy))
        scaled.append(
            PackedPlacement(
                source_path=p.source_path,
                polygon=affinity.translate(source.hull, xoff=x, yoff=y),
                angle_degrees=0.0,
                flipped=False,
                top_left=(x, y),
                image=p.image,
            )
        )
    return _adjust_to_canvas(scaled, options)
